export const ONOPEN = 'ONOPEN'
export const RECONNECT = 'RECONNECT'
export const HEARTBEAT = 'HEARTBEAT'
export const DATA_SERVER_ONOPEN = 'DATA_SERVER_ONOPEN'
export const DATA_SERVER_RECONNECT = 'DATA_SERVER_RECONNECT'
export const DATA_SERVER_HEARTBEAT = 'DATA_SERVER_HEARTBEAT'
export const ACCOUNT_LOGON_VERIFY = 'ACCOUNT_LOGON_VERIFY'

export const ACCOUNT_BALANCE = 'ACCOUNT_BALANCE'

